
# SEO settings
title: "Primarily"
title2: "Software" # default: ""
description: "A place to write about .NET, DDD, Functional Programming, Machine Learning, and whatever else may pique my interest"
keywords: ".NET, DDD, Functional Programming, Machine Learning, C#, F#"
url: http://primarilysoftware.github.io/ # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/primarilysoftware/primarilysoftware.githib.io
disqus_shortname: "primarilysoftware"
twitter_username: "primarilysoftware"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jon Guy"
  job      : "Software Engineer"
  bio      : "Been doing software development since 2010, focused mainly in .NET"
  thumb    : /images/author.jpg
  email    : jon@primarilysoftware.com
  url      : http://primarilysoftware.github.io
  github   : http://github.com/primarilysoftware
  twitter  : http://twitter.com/primarilysoftware
  linkedin : http://linkedin.com/in/jwguy

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@PrimarilySoftware"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
